### ISSUE TITLE
Monte carlo timeout

### ISSUE THREAD

**Issue by CarlitoS476** [dickreuter/Poker#131]
Is there a hardware requirement to process the monte carlo simulation within the time constraints of a PokerStars Zoom table? 
It seems to work 95% but occasionally fails to make a decision in time (I'm unfamiliar with the math so not sure if its coincidence or by design but this seems to happen more often when its presented with a strong hand i.e. pocket As). 

I've also noticed that both PP and PS can take advantage of hotkey inputs for all commands, is there a reason why direct mouse control is preferred over this method?

**Comment by dickreuter** [comment]
the hand has no influence on the calculation, as it just runs
simulation.s If the timeout is too high, you may adjust the value in
settings.

Didn't know about the hotkeys. Myabe this would be something to add in
the future. But the mouse is not really an issue, the problem is the
recogniztion of the numbers. And this probably takes more time than
the montecarlo.

Make sure to use an ssd hard disk, that will significantly speed up
tesseract, which is used for the OCR of the numbers.

**Comment by CarlitoS476** [comment]
Thanks for the clarification, I assume there would be an impact on the accuracy of the decision maker by reducing the time its allowed to run?

As for OCR, I am already using an SSD. I will explore the possibility of using a RAMDisk as this may have potential for significant improvement.

**Comment by CarlitoS476** [comment]
Has run without timeouts on a RAMDisk for the last couple of days, have not had an opportunity to test NVMe but this seems like a viable solution for those with SATA limitations
