### ISSUE TITLE
Bot Taking Too Long to Make Move

### ISSUE THREAD

**Issue by Bonobo791** [dickreuter/Poker#161]
**Describe the bug**
Bot is taking too long to processes decisions in order to beat the timer. Could this simply be an issue of my computer? Code optimization? Any thoughts? I can work on the project if it's a code issue.

I've emailed @dickreuter  on this issue. Not sure if anyone else can assist. @dexion @vidmantasb @rjjeffries @swizes 

Details:
DELL w/ Windows 10 Laptop
11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
8 cores, 16 processors
RAM: 16.0 GB (15.7 GB usable)

**Screenshot png file from the log\screenshots folder**
Nothing to share.

**Log information**
Nothing to share.

**Comment by ryanwood1** [comment]
Hi.
Did you get any where with this?
Bot seems to hang making decisions then times out, then makes the decision long after the time out happens.

**Comment by Bonobo791** [comment]
No. The project is dead, I believe. You will have to do the edits yourself.

Em dom., 30 de out. de 2022 5:37 PM, ryanwood1 ***@***.***>
escreveu:

**Comment by dickreuter** [comment]
The project is not dead but there are currently no priorities on improving
speed.

**Comment by Bonobo791** [comment]
What are the priorities?

**Comment by cdsimmons** [comment]
@Bonobo791 Did you make any progress?

Since its screen scraping, I would imagine some gains could be made by switching to a memory reading solution. Not sure if that would resolve the no-decision issue you're having though, and from what I have seen its quite difficult to search for memory patterns with PokerStars since they seem to change between updates.
