### ISSUE TITLE
Player position

### ISSUE THREAD

**Issue by swizes** [dickreuter/Poker#20]
Hello, 

First of all "Great Job, I bow before you". I have tried the bot with partypoker and the bot finds my cards only in one seat position. Is it meant to be like that? Because sometimes the game puts me in random seat and the bot can't recognize my pot and cards.

Pokerstars setup gives exception error, I will put a screenshot of terminal so you can check it out.
![pokerbot_debug_error](https://cloud.githubusercontent.com/assets/8876645/19548946/a6a76f22-96a1-11e6-9fae-1782278dab65.PNG)

Kind Regards

**Comment by dickreuter** [comment]
The error you describe has nothing to do with the position. It shows that the bet button png is missing for poker stars (which we haven't tested for a while as we were focusing on partypoker). We need to add that .png (in pics/ps in the same way as it is in pics/pp) with photoshop. 

The bot is designed for fast forward games where the player is always in the same position. Currently it won't work otherwise.

**Comment by swizes** [comment]
Ok, it explains everything. Thank you

**Comment by dickreuter** [comment]
You can keep the issue open unless you added the button :)
